# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Upgrade NPM
      run: npm -g install npm

    - name: Install packages
      run: npm i --workspaces

    - name: Build packages
      run: npm run build --workspaces --if-present

    - name: Test packages
      run: npm run test --workspaces --if-present

    # You may pin to the exact commit or the version.
    # uses: codecov/codecov-action@6004246f47ab62d32be025ce173b241cd84ac58e
    - uses: codecov/codecov-action@v2.1.0
      with:
        # Comma-separated list of files to upload
        files: ./packages/url-manager/coverage/coverage-final.json,./packages/object-util/coverage/coverage-final.json,./packages/easy-sitemap/coverage/coverage-final.json # optional
