# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.4.1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Upgrade NPM
      run: npm -g install npm

    - name: Install packages
      run: npm i && npm i --workspaces

    - name: Build packages
      run: npm run build --workspaces --if-present

    - name: Test packages
      run: npm run test --workspaces --if-present

    - uses: sonarsource/sonarcloud-github-action@master
      if: matrix.node-version == '16.x'
      with:
        args: >
          -Dsonar.organization=dzeio
          -Dsonar.projectKey=dzeiocom_libs
          -Dsonar.javascript.lcov.reportPaths=packages/**/coverage/lcov.info
          -Dsonar.testExecutionReportPaths=packages/easy-sitemap/test-report.xml,packages/object-util/test-report.xml,packages/url-manager/test-report.xml
          -Dsonar.sources=packages
          -Dsonar.verbose=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
